/**
 * Syncs packages/contracts/deployments/*.json into a typed address book (src/generated/deployments.ts)
 * and exports per-contract ABI JSON files (abi-json/*.json) for the indexer.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const deploymentsDir = join(root, "../contracts/deployments");
const outFile = join(root, "src/generated/deployments.ts");
const abiOut = join(root, "abi-json");
const forgeOut = join(root, "../contracts/out");

type Deployment = Record<string, string | number>;
const deployments: Record<string, Deployment> = {};
if (existsSync(deploymentsDir)) {
  for (const f of readdirSync(deploymentsDir).filter((x) => x.endsWith(".json"))) {
    const d = JSON.parse(readFileSync(join(deploymentsDir, f), "utf8")) as Deployment;
    deployments[String(d.chainId)] = d;
  }
}

const body = `// AUTO-GENERATED by scripts/sync-deployments.ts — do not edit.
import type { Address } from "viem";

export type DeploymentRecord = {
  network: string;
  chainId: number;
  startBlock: number;
  deployedAt: number;
  deployer: Address;
  quote: Address;
  /** Open-mint test quote (mUSDC), allowlisted next to \`quote\` — script/TestQuote.s.sol. Absent on mainnet. */
  testQuote?: Address;
  factory: Address;
  amm: Address;
  vault: Address;
  router: Address;
  raiseImpl: Address;
  treasuryImpl: Address;
  projectTokenImpl: Address;
  conditionalTokenImpl: Address;
};

export const deployments: Record<number, DeploymentRecord> = ${JSON.stringify(deployments, null, 2)} as const as unknown as Record<number, DeploymentRecord>;
`;
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
console.log(`✓ deployments: chains ${Object.keys(deployments).join(", ") || "(none)"}`);

mkdirSync(abiOut, { recursive: true });
const contracts = [
  "MonetaFactory",
  "Raise",
  "Treasury",
  "ProjectToken",
  "ConditionalVault",
  "ConditionalToken",
  "MonetaAMM",
  "MonetaRouter",
];
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(forgeOut, `${name}.sol/${name}.json`), "utf8"));
  writeFileSync(join(abiOut, `${name}.json`), JSON.stringify(artifact.abi, null, 2));
}
console.log(`✓ abi-json: ${contracts.length} contracts`);
