/**
 * Generates config.yaml for a network from packages/contracts/deployments/<chainId>.json, so indexer addresses and
 * start blocks can never drift from the actual deployment. Usage: tsx scripts/gen-config.ts <local|testnet>
 *   local   → chain 31337 via RPC (anvil)
 *   testnet → chain 10143 via HyperSync (ENVIO_API_TOKEN) or, without a token, the Monad testnet RPC
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const network = process.argv[2] ?? "local";
const chainId = network === "testnet" ? 10143 : 31337;
const deployment = JSON.parse(
  readFileSync(join(here, `../../../packages/contracts/deployments/${chainId}.json`), "utf8"),
) as Record<string, string | number>;

const abi = (name: string) => `../../packages/sdk/abi-json/${name}.json`;
// Testnet: HyperSync when ENVIO_API_TOKEN is set (first-class Monad support, no RPC limits on backfill);
// otherwise plain RPC, which is fine for a fresh deployment's short block range. Monad testnet is a HyperSync
// chain, so a bare `rpc: <url>` would only be a fallback (and HyperSync refuses to run without a token):
// the RPC must be marked `for: sync` to become the data source. Monad's RPC caps eth_getLogs at 100 blocks.
const source =
  network === "testnet"
    ? process.env.ENVIO_API_TOKEN
      ? `    # HyperSync (first-class Monad testnet support) — no RPC limits on backfill`
      : `    rpc:
      url: ${process.env.MONAD_TESTNET_RPC_URL || "https://testnet-rpc.monad.xyz"}
      for: sync
      initial_block_interval: 100
      interval_ceiling: 100`
    : `    rpc: ${process.env.LOCAL_RPC_URL ?? "http://127.0.0.1:8545"}`;

const yaml = `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# AUTO-GENERATED by scripts/gen-config.ts for "${network}" — do not edit; edit the generator instead.
name: moneta-indexer
description: Moneta read models — raises, projects, proposals, pools, candles, positions
rollback_on_reorg: true
field_selection:
  transaction_fields:
    - hash
contracts:
  - name: MonetaFactory
    abi_file_path: ${abi("MonetaFactory")}
    events:
      - event: RaiseCreated
      - event: ProjectLaunched
  - name: Raise
    abi_file_path: ${abi("Raise")}
    events:
      - event: Contributed
      - event: RaiseFinalized
      - event: RaiseAborted
      - event: Claimed
  - name: Treasury
    abi_file_path: ${abi("Treasury")}
    events:
      - event: Launched
      - event: ProposalCreated
      - event: ProposalActivated
      - event: ProposalFinalized
      - event: ProposalExecuted
      - event: ProposalExecutionFailed
      - event: ProposalCancelled
      - event: BondSettled
      - event: LiquidityRestored
      - event: TrancheReleased
      - event: BudgetClaimed
      - event: BudgetRateSet
      - event: FounderSet
      - event: Minted
      - event: TransferExecuted
      - event: BuybackExecuted
      - event: CallExecuted
      - event: RedemptionStarted
      - event: RedemptionClaimed
      - event: PerformanceUnlocked
  - name: ProjectToken
    abi_file_path: ${abi("ProjectToken")}
    events:
      - event: Transfer
  - name: ConditionalVault
    abi_file_path: ${abi("ConditionalVault")}
    events:
      - event: ConditionalTokensCreated
      - event: Resolved
  - name: ConditionalToken
    abi_file_path: ${abi("ConditionalToken")}
    events:
      - event: Transfer
  - name: MonetaAMM
    abi_file_path: ${abi("MonetaAMM")}
    events:
      - event: PoolCreated
      - event: LiquidityAdded
      - event: LiquidityRemoved
      - event: Swap
      - event: ObservationUpdated
      - event: PoolClosed
  - name: MonetaRouter
    abi_file_path: ${abi("MonetaRouter")}
    events:
      - event: OutcomeTraded
chains:
  - id: ${chainId}
    start_block: ${deployment.startBlock}
${source}
    contracts:
      - name: MonetaFactory
        address: "${deployment.factory}"
      - name: ConditionalVault
        address: "${deployment.vault}"
      - name: MonetaAMM
        address: "${deployment.amm}"
      - name: MonetaRouter
        address: "${deployment.router}"
      - name: Raise
      - name: Treasury
      - name: ProjectToken
      - name: ConditionalToken
`;
writeFileSync(join(here, "../config.yaml"), yaml);
console.log(
  `✓ config.yaml for ${network} (chain ${chainId}, start block ${deployment.startBlock})`,
);
