/**
 * Generates the indexer config from packages/contracts/deployments/<chainId>.json, so indexer addresses and start
 * blocks can never drift from the actual deployment. Usage: tsx scripts/gen-config.ts <local|testnet|cloud>
 *   local   → config.yaml, chain 31337 via RPC (anvil)
 *   testnet → config.yaml, chain 10143 via HyperSync (ENVIO_API_TOKEN) or, without a token, the Monad testnet RPC
 *   cloud   → config.cloud.yaml (committed), chain 10143 via HyperSync, for Envio Cloud
 * Envio Cloud only uploads this directory, so the ABIs are copied into abis/ (committed) and referenced from there.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const network = process.argv[2] ?? "local";
if (!["local", "testnet", "cloud"].includes(network))
  throw new Error(`unknown network: ${network}`);
const chainId = network === "local" ? 31337 : 10143;
const outFile = network === "cloud" ? "config.cloud.yaml" : "config.yaml";
const deploymentFile = join(root, `../../packages/contracts/deployments/${chainId}.json`);
if (!existsSync(deploymentFile)) {
  // Outside the monorepo (Envio Cloud uploads only this directory): keep the committed config and ABIs as they are.
  console.log(`• ${deploymentFile} not found — using the committed config`);
  process.exit(0);
}
const deployment = JSON.parse(readFileSync(deploymentFile, "utf8")) as Record<
  string,
  string | number
>;

// Refresh the committed ABI copies from the SDK's export (regenerated by `pnpm --filter @moneta/sdk generate`).
const CONTRACTS = [
  "MonetaFactory",
  "Raise",
  "Treasury",
  "ProjectToken",
  "ConditionalVault",
  "ConditionalToken",
  "MonetaAMM",
  "MonetaRouter",
];
mkdirSync(join(root, "abis"), { recursive: true });
for (const name of CONTRACTS) {
  copyFileSync(
    join(root, `../../packages/sdk/abi-json/${name}.json`),
    join(root, `abis/${name}.json`),
  );
}
const abi = (name: string) => `abis/${name}.json`;

// Testnet: HyperSync when ENVIO_API_TOKEN is set (first-class Monad support, no RPC limits on backfill);
// otherwise plain RPC, which is fine for a fresh deployment's short block range. Monad testnet is a HyperSync
// chain, so a bare `rpc: <url>` would only be a fallback (and HyperSync refuses to run without a token):
// the RPC must be marked `for: sync` to become the data source. Monad's RPC caps eth_getLogs at 100 blocks.
// Envio Cloud always has HyperSync.
const source =
  network === "local"
    ? `    rpc: ${process.env.LOCAL_RPC_URL ?? "http://127.0.0.1:8545"}`
    : network === "cloud" || process.env.ENVIO_API_TOKEN
      ? `    # HyperSync (first-class Monad testnet support) — no RPC limits on backfill`
      : `    rpc:
      url: ${process.env.MONAD_TESTNET_RPC_URL || "https://testnet-rpc.monad.xyz"}
      for: sync
      initial_block_interval: 100
      interval_ceiling: 100`;

const yaml = `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# AUTO-GENERATED by \`pnpm gen-config ${network}\` (scripts/gen-config.ts) — do not edit; edit the generator instead.
name: moneta-indexer
description: Moneta read models — raises, projects, proposals, pools, candles, positions
rollback_on_reorg: true
field_selection:
  transaction_fields:
    - hash
contracts:
  - name: MonetaFactory
    abi_file_path: ${abi("MonetaFactory")}
    events:
      - event: RaiseCreated
      - event: ProjectLaunched
  - name: Raise
    abi_file_path: ${abi("Raise")}
    events:
      - event: Contributed
      - event: RaiseFinalized
      - event: RaiseAborted
      - event: Claimed
  - name: Treasury
    abi_file_path: ${abi("Treasury")}
    events:
      - event: Launched
      - event: ProposalCreated
      - event: ProposalActivated
      - event: ProposalFinalized
      - event: ProposalExecuted
      - event: ProposalExecutionFailed
      - event: ProposalCancelled
      - event: BondSettled
      - event: LiquidityRestored
      - event: TrancheReleased
      - event: BudgetClaimed
      - event: BudgetRateSet
      - event: FounderSet
      - event: Minted
      - event: TransferExecuted
      - event: BuybackExecuted
      - event: CallExecuted
      - event: RedemptionStarted
      - event: RedemptionClaimed
      - event: PerformanceUnlocked
  - name: ProjectToken
    abi_file_path: ${abi("ProjectToken")}
    events:
      - event: Transfer
  - name: ConditionalVault
    abi_file_path: ${abi("ConditionalVault")}
    events:
      - event: ConditionalTokensCreated
      - event: Resolved
  - name: ConditionalToken
    abi_file_path: ${abi("ConditionalToken")}
    events:
      - event: Transfer
  - name: MonetaAMM
    abi_file_path: ${abi("MonetaAMM")}
    events:
      - event: PoolCreated
      - event: LiquidityAdded
      - event: LiquidityRemoved
      - event: Swap
      - event: ObservationUpdated
      - event: PoolClosed
  - name: MonetaRouter
    abi_file_path: ${abi("MonetaRouter")}
    events:
      - event: OutcomeTraded
chains:
  - id: ${chainId}
    start_block: ${deployment.startBlock}
${source}
    contracts:
      - name: MonetaFactory
        address: "${deployment.factory}"
      - name: ConditionalVault
        address: "${deployment.vault}"
      - name: MonetaAMM
        address: "${deployment.amm}"
      - name: MonetaRouter
        address: "${deployment.router}"
      - name: Raise
      - name: Treasury
      - name: ProjectToken
      - name: ConditionalToken
`;
writeFileSync(join(root, outFile), yaml);
console.log(`✓ ${outFile} for ${network} (chain ${chainId}, start block ${deployment.startBlock})`);
